name: Run Tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        PYTHONPATH: .
      run: |
        if [ -d "tests" ] && [ "$(find tests -name "test_*.py" -type f)" ]; then
          echo "Running tests..."
          python -m pytest tests/ -v
        else
          echo "No test files found, skipping tests"
          exit 0
        fi